### PR TITLE
Fixing the quotes around the AMI id.

### PR DESCRIPTION
**Pull request by vcardillo**
Sorry this took a little while. I built the docker image from this change, pushed it to our Docker Hub, and tested with our Concourse pipeline. Looks to be working.

Ref: #1

### CODE REVIEW

**Comment by vcardillo** [comment]
As an aside, it looks like `resource_types` are unique in Concourse, not `resources`. So I had to rename the `resource_type`.`name` in the pipeline.yml file, in order to get Concourse to stop using the cache and run `in` again (since Canonical has unsurprisingly not published a new AMI within the last few days).

**Comment by vcardillo** [comment]
@jdub?

**Comment by jdub** [comment]
Sorry, will merge now!

**Comment by jdub** [comment]
Done. Thanks for finding this and doing the PR! 😄

**Pull request merged**
